### ISSUE TITLE
[1.0] Feature List

### ISSUE THREAD

**Issue by jlengstorf** [gramps-graphql/gramps#30]
These are the features we want to have for 1.0.

~~- [ ] Refactor: Move to Typescript~~ #27 <-- will revisit

- [x] Feature: Update export format to be compatible with external frameworks #26 
- [x] Docs: Write documentation #28 
- [x] Docs: Update README #29

**Comment by jlengstorf** [comment]
For anyone who's got [ZenHub](https://www.zenhub.com/), I'm trying to manage who's doing what/what stage we're in through there. If you have it (it's free and pretty awesome for teams if you don't), the [GrAMPS boards are here](https://github.com/gramps-graphql/gramps/issues#boards).

**Comment by timrs2998** [comment]
Is ZenHub only for members of the gramps-graphql org? Otherwise I'm curious on the status of the 1.0 release and the direction of GrAMPS

**Comment by jlengstorf** [comment]
ZenHub is a [free browser add-on](https://www.zenhub.com/extension) that gives you an agile-ish board view of issues:
<img width="1440" alt="screencap-by-jlengstorf" src="https://user-images.githubusercontent.com/163561/33616863-c3d982b0-d9a3-11e7-9377-fca23d531962.png">

I got snowed under over the holiday, and I'm putting out some fires at IBM right now, but I'm planning to resume work on GrAMPS 1.0 to try and get us there by the end of the year. The biggest blocker right now is finalizing the CLI API (see https://github.com/gramps-graphql/gramps-cli/issues/9) — I don't want to start working on that if we haven't agreed on what it should look like.

**Comment by timrs2998** [comment]
Awesome thanks for the updates, we really appreciate it; @Piefayth you may be interested

**Comment by jlengstorf** [comment]
Closing this — 1.x is now live! 🎉
